export const SET_USER = 'SET_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_LOADING = 'SET_LOADING';
export const SET_EXPANDED_DRAWER = 'SET_EXPANDED_DRAWER';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME';
